language: php

notifications:
  email:
    recipients:

sudo: false

addons:
  postgresql: "9.6" 

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2
  - 7.3

env:
  global:
    - DB=pgsql
  matrix:
    - MOODLE_BRANCH=MOODLE_34_STABLE
    - MOODLE_BRANCH=MOODLE_35_STABLE
    - MOODLE_BRANCH=MOODLE_36_STABLE
    - MOODLE_BRANCH=MOODLE_37_STABLE
    - MOODLE_BRANCH=master

matrix:
  include:
    # Test with MySQL
    - php: 7.3
      env: DB=mysqli MOODLE_BRANCH=master
    # Test with PHP 7.3
    - php: 7.3
      env: MOODLE_BRANCH=master
  exclude:
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_34_STABLE
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_35_STABLE

before_install:
  - export MOODLE_VERSION=$(echo "$MOODLE_BRANCH" | cut -d'_' -f 2)
  - phpenv config-rm xdebug.ini
  - if [ "$MOODLE_VERSION" = 36 ] || [ "$MOODLE_VERSION" -le 34 ]; then NVMVERSION=8.9; else NVMVERSION=14.0.0; fi
  - nvm install $NVMVERSION;
  - nvm use $NVMVERSION;
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install -vvv
  - >
    if [ "$MOODLE_BRANCH" == 'MOODLE_34_STABLE' ] || [ "$MOODLE_BRANCH" == 'MOODLE_35_STABLE' ]; then
      (cd moodle; git fetch origin master; git cherry-pick 99405aa7e2a34174a3eeaf9f9ffc9db3bc9f6192;);
    fi

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
